config/routes.rb
Rails.application.routes.draw do
    devise_for :users

    root 'users#index'
  
    # Commented to prevent defaulting to sign in view to check if signed in or not
    # devise_scope :user do
    #   root 'devise/sessions#new'
    # end
  
    resources :users, only: [:index, :show] do 
      resources :posts, only: [:index, :show, :new, :create, :destroy] do
        resources :comments, only: [:index, :create, :destroy] 
        resources :likes, only: [:index, :create, :destroy]
      end
    end

    namespace :api, defaults: { format: :json } do
      namespace :v1 do
        resources :users, only: [:index, :show] do 
          resources :posts, only: [:index, :show, :new, :create, :destroy] do
            resources :comments, only: [:index, :new, :create, :destroy] 
            resources :likes, only: [:index, :create, :destroy]
          end
        end
      end
    end
    
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id, dependent: :delete_all
  has_many :comments, foreign_key: :author_id, dependent: :delete_all
  has_many :likes, foreign_key: :author_id, dependent: :delete_all

  validates :name, presence: true, length: { maximum: 250 }

  validates :posts_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def latest_three_posts
    posts.order(created_at: :desc).limit(3)
  end

  def first_three_posts
    posts.order(created_at: :asc).limit(3)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  def index
    @users = User.all

    respond_to do |format|
      format.json { render json: @users, status: 200 }
    end
  end

  def show
    if params[:id] == 'sign_out'
      sign_out current_user
      redirect_to new_user_session_path, notice: 'Sign out succesfully' unless @user
      format.json { render status: 200 }
    else
      @user = User.find_by(id: params[:id])
      respond_to do |format|
        redirect_to users_path, notice: 'User found' unless @user
        format.json { render json: @user, status: 200 }
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.json { render json: @users, status: 200 }
    end
  end

  def show
    if params[:id] == 'sign_out'
      sign_out current_user
      redirect_to new_user_session_path, notice: 'Sign out succesfully' unless @user
    else
      @user = User.find_by(id: params[:id])
      respond_to do |format|
        format.html { redirect_to users_path, notice: 'User found' unless @user }
        format.json { render json: @user, status: 200 }
      end
    end
  end
end

app/controllers/users_controllers.rb
UsersController < ApplicationController
def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Channel logic can be defined here
end

app/views/users/index.html.erb
<main>
    <section class="section1">

    <% @users.each do |user| %>
        <article class="home_cards">
            <figure>
                <img src=<%= user.photo %> alt='<%= user.name %>'>
            </figure>
            <div class="home_cards_details">
            <h2></h2>
                <h3>Username: <%= link_to user.name, user_path(user.id), class:"td_none" %></h3>
                <span>Number of posts: <%= user.posts_counter %></span>
            </div>
        </article>
    <% end %>

    </section>
</main>

app/views/users/show.html.erb
<main>
        <section>
            <article class="home_cards">
                <figure>
                    <img src=<%= @user.photo %> alt="<%= @user.name %>">
                </figure>
                <div class="home_cards_details">
                    <h3>Username: <%= @user.name %></h3>
                    <p>Number of posts: <%= @user.posts_counter %></p>
                </div>
            </article>
        </section>

        <section class="user_details_bio_section">
            <header>
                <h3>Bio</h3>
            </header>
            <article>
                <p><%= @user.bio %></p>
            </article>
        </section>

        <section class="user_details_post_section">
            <% @user.latest_three_posts.each do |post| %>
            <%= link_to user_post_path(@user.id, post.id), class:"td_none" do %>
            <article>
                <header> <h3><%= post.title %></h3></header>
                <div><p><%= post.text %></p></div>
            </article>
            <% end %>
            <% end %>
            

            <div class="see_all_btnbox">
                <button><%= link_to "See all posts", user_posts_path(@user), class:"td_none" %></button> 
            </div>
            <br>
            <div class="see_all_btnbox">
                <button><%= link_to "Create new post", new_user_post_path(@user.id), class:"td_none" %></button>
            </div>
        </section>
    </main>
    