config/routes.rb
Rails.application.routes.draw do
    devise_for :users

    root 'users#index'
  
    # Commented to prevent defaulting to sign in view to check if signed in or not
    # devise_scope :user do
    #   root 'devise/sessions#new'
    # end
  
    resources :users, only: [:index, :show] do 
      resources :posts, only: [:index, :show, :new, :create, :destroy] do
        resources :comments, only: [:index, :create, :destroy] 
        resources :likes, only: [:index, :create, :destroy]
      end
    end

    namespace :api, defaults: { format: :json } do
      namespace :v1 do
        resources :users, only: [:index, :show] do 
          resources :posts, only: [:index, :show, :new, :create, :destroy] do
            resources :comments, only: [:index, :new, :create, :destroy] 
            resources :likes, only: [:index, :create, :destroy]
          end
        end
      end
    end
    
  end

app/views/shared_features/_footer.html.erb
<footer class="footer_box">
        <div>
            <p>Copyright &#169;2023</p>
        </div>
    </footer>

app/views/shared_features/_header.html.erb
<header class="nav_header">
<div class="logo_box list_style_none">  
    <li><%= link_to "BlogRails", root_path, class:"td_none" %></li>
</div>

<nav class="nav_box">
    <ul class="list_style_none">
        <li><%= link_to "Home", root_path, class:"td_none" %></li>
        <li><a class="td_none" href="#">User Detail</a> </li>
        <li><a class="td_none" href="#">Most Viewed</a> </li>
        <li><a class="td_none" href="#">Profile</a> </li> 
    </ul>
</nav>
</header>

app/views/shared_features/_likeforms.html.erb
<section>
  <%= form_with model: Like, url: user_post_likes_path(@post.author, @post) do |f| %>
     <%= f.submit 'Like Post' %>
     <% end %>

</section>