config/routes.rb
Rails.application.routes.draw do
    devise_for :users

    root 'users#index'
  
    # Commented to prevent defaulting to sign in view to check if signed in or not
    # devise_scope :user do
    #   root 'devise/sessions#new'
    # end
  
    resources :users, only: [:index, :show] do 
      resources :posts, only: [:index, :show, :new, :create, :destroy] do
        resources :comments, only: [:index, :create, :destroy] 
        resources :likes, only: [:index, :create, :destroy]
      end
    end

    namespace :api, defaults: { format: :json } do
      namespace :v1 do
        resources :users, only: [:index, :show] do 
          resources :posts, only: [:index, :show, :new, :create, :destroy] do
            resources :comments, only: [:index, :new, :create, :destroy] 
            resources :likes, only: [:index, :create, :destroy]
          end
        end
      end
    end
    
  end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes, foreign_key: :post_id, dependent: :delete_all
  has_many :comments, foreign_key: :post_id, dependent: :delete_all

  after_save :update_post_counter
  after_destroy :decrement_post_counter

  validates :title, presence: true
  validates :comments_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def latest_five_comments
    comments.order(created_at: :desc).limit(5)
  end

  def update_post_counter
    author.update(posts_counter: author.posts.all.length)
  end

  def decrement_post_counter
    author.decrement!(:posts_counter)
  end

  private :update_post_counter, :decrement_post_counter
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = Post.all.includes(:comments)

    respond_to do |format|
      format.json { render json: @posts, status: 200 }
    end
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])

    respond_to do |format|
      format.json { render json: @post, status: 200 }
    end
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:success] = 'Post has benn created successfully'
      redirect_to user_post_path(current_user, @post)
    else
      flash.now[:error] = 'Error: Post was not created !!'
      render :new
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @post.destroy
    redirect_to user_posts_path(@user)
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end

  private :post_params
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = Post.all.includes(:comments)
    respond_to do |format|
      format.html
      format.json { render json: @posts, status: 200 }
    end
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @post, status: 200 }
    end
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:success] = 'Post has benn created successfully'
      redirect_to user_post_path(current_user, @post)
    else
      flash.now[:error] = 'Error: Post was not created !!'
      render :new
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @post.destroy
    redirect_to user_posts_path(@user)
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
  private :post_params
end

app/helpers/posts_helper.rb
module PostsHelper
  # Channel logic can be defined here
end

app/views/posts/index.html.erb
<main>
        <section class="post_section1">
            <article class="home_cards">
                <figure>
                    <img src='<%= @user.photo %>' alt='<%= @user.name %>'>
                </figure>
                <div class="home_cards_details">
                    <h3>Username: <%= @user.name %></h3>
                    <p>Number of posts: <%= @user.posts_counter %></p>
                </div>
            </article> 
        </section>
        
        <section class="post_page_post_details">
        <% @user.posts.each do |post| %>
            <article>
                <div class="post_page_post_details_div" >
                    <header>
                    <h3>
                        <%= link_to post.title, user_post_path(@user, post), class:"td_none" %>
                    </h3>
                    </header>
                    <div><p><%= post.text %></p></div>

                    <ul class="post_page_interaction list_style_none">
                        <li>Comments: <%= post.comments_counter || 0%></li>
                        <li>Likes: <%= post.likes_counter || 0 %> </li>
                    </ul>

                </div>

                <ul class="post_page_user_comment_box list_style_none">
                <% if !post.latest_five_comments %>
                 <li>No comments added!</li>  
                   <% else %>
                    <% post.latest_five_comments.includes(:author).each do |comment| %>
                    <li><%= comment.author.name %>: <%= comment.text %></li> 
                 <% end %>
                <% end %>
                </ul>
                
            </article>
 <% end %>
        </section>

        <div class="post_page_pagination">
            <ul class="list_style_none">
                <li>Page 1</li>
                <li>Page 2</li>
                <li>Page 3</li>
                <li>Page 4</li>
            </ul>
        </div>
    </main>

app/views/posts/new.html.erb
<section class="container">
<p class="post-title"> Add New Post :</p>
<%= form_with model: @post, url: user_posts_path do |f| %>
     <div>
     <%= f.label :title %> <br>
     <%= f.text_field :title %>
     </div>

     <div>
     <%= f.label :text %> <br>
     <%= f.text_field :text, placeholder: "Enter post text", row: 40, required: true %>
     </div>
     <br>
     <div>
     <%= f.submit "Submit Post" %>
     </div>
<% end %>

</section>

app/views/posts/show.html.erb
<main>
        <section class="post_details_section1">
            <article class="post_details_section1_card">
                <header>
                    <h3><%= @post.title %> by <%= @post.author.name %></h3>
                    <ul class="post_interaction list_style_none">
                        <li>Comments: <%= @post.comments_counter || 0 %></li>
                        <li>Likes: <%= @post.likes_counter || 0 %></li>
                    </ul>
                </header>
                
                <div class="post_details_section1_card_text">
                    <p><%= @post.text %></p>
                </div>
            </article> 

            <ul class="post_details_section1_user_comment_box list_style_none">
             <% @post.latest_five_comments.includes(:author).each do |comment| %>
                <li> <%= comment.author.name %>: <%= comment.text %></li>
                <br>
                <% if can? :destroy, comment %>
                <button class="login_btn">
                <%= link_to 'Delete Comment', user_post_comment_path(@user, comment.post, comment.id) , data: { turbo_method: :delete,
                    turbo_confirm: "Are you sure you want to delete Comment?"
                  } %>
                </button>
                <% end %>
             <% end %>
            </ul>

            <br><br>
            <div><%= render "comments/form" %> </div>
            <div><%= render "shared_features/likeforms" %></div>
 

            <div>
                <% if can? :destroy, @post%>
                    <button class='login_btn'>
                    <%= link_to 'Delete Post', user_post_path(@user, @post), data: { turbo_method: :delete,
                    turbo_confirm: "Are you sure you want to delete Post?"} %>
                    </button>
                <% end %>
            </div>

        </section>
</main>